import React,{useEffect,useMemo,useState} from 'react';
import {Platform,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {supabase} from './backend';
import {FinanceReport,FinanceLine,FinancePayment,money,kilos,localDay,monthName,totals,advances,csv} from './finance';
import {financePdf} from './financePdf';

const empty:FinanceReport={lines:[],payments:[],rules:[],revisions:[]};
const style=StyleSheet.create({card:{padding:18,backgroundColor:'#fffdf7',borderWidth:1,borderColor:'#d8e1d3',borderRadius:16,marginVertical:10,gap:9},heading:{fontSize:23,fontWeight:'700',color:'#164b3a'},sub:{fontSize:18,fontWeight:'700',color:'#164b3a',marginTop:8},text:{fontSize:16,color:'#203c32'},small:{fontSize:14,color:'#55695d'},error:{fontSize:16,color:'#a52222'},button:{backgroundColor:'#164b3a',padding:13,borderRadius:10,marginVertical:4},buttonText:{color:'#fff',fontSize:16,fontWeight:'700',textAlign:'center'},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd6cb',borderRadius:10,padding:12,fontSize:16},row:{paddingVertical:8,borderBottomWidth:1,borderBottomColor:'#dde4d8'},table:{flexDirection:'row',gap:6},cell:{flex:1,fontSize:13,color:'#203c32'}});
const Button=({label,onPress,disabled=false}:{label:string;onPress:()=>void;disabled?:boolean})=><Pressable onPress={onPress} disabled={disabled} style={[style.button,disabled&&{opacity:.5}]}><Text style={style.buttonText}>{label}</Text></Pressable>;
const Input=({label,value,onChange,placeholder}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string})=><View><Text style={style.small}>{label}</Text><TextInput accessibilityLabel={label} style={style.input} value={value} onChangeText={onChange} placeholder={placeholder}/></View>;
const parseAmount=(s:string,decimals:number)=>{const n=Number(s.trim().replace(',','.'));if(!Number.isFinite(n)||n<=0||n>1000000||Math.round(n*10**decimals)!==n*10**decimals)throw Error(`Escribe un importe positivo con máximo ${decimals} decimales`);return n};
const download=(blob:Blob,name:string)=>{const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000)};
const fileName=(s:string)=>s.replace(/[^a-zA-Z0-9_-]/g,'_').slice(0,60);

export default function FinancePanel({organizationId,clients,people,practice}:{organizationId:string;clients:string[];people:{id:string;full_name:string}[];practice:boolean}){
 const [report,setReport]=useState<FinanceReport>(empty),[busy,setBusy]=useState(false),[error,setError]=useState(''),[loaded,setLoaded]=useState(false),[section,setSection]=useState<'deliveries'|'payments'>('deliveries');
 const [client,setClient]=useState(''),[year,setYear]=useState(''),[month,setMonth]=useState('');
 const [priceTrip,setPriceTrip]=useState(''),[price,setPrice]=useState(''),[reason,setReason]=useState(''),[rateFrom,setRateFrom]=useState('');
 const [paymentDate,setPaymentDate]=useState(localDay(new Date().toISOString())),[paymentAmount,setPaymentAmount]=useState(''),[reference,setReference]=useState(''),[allocationInputs,setAllocationInputs]=useState<Record<string,string>>({}),[receipt,setReceipt]=useState<File|null>(null);
 const [advanceId,setAdvanceId]=useState(''),[reversalId,setReversalId]=useState(''),[reversalReason,setReversalReason]=useState('');
 const refresh=async()=>{if(!supabase)throw Error('No hay conexión con Supabase');const {data,error}=await supabase.rpc('finance_report',{p_org:organizationId});if(error)throw Error(error.message);setReport(data as FinanceReport);setLoaded(true)};
 useEffect(()=>{let active=true;setLoaded(false);if(!supabase)return;supabase.rpc('finance_report',{p_org:organizationId}).then(({data,error})=>{if(!active)return;if(error)setError(`No se pudieron cargar finanzas: ${error.message}`);else{setReport(data as FinanceReport);setLoaded(true)}});return()=>{active=false}},[organizationId]);
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();await refresh()}catch(e){setError(String(e))}finally{setBusy(false)}};
 const names=useMemo(()=>Array.from(new Set([...clients,...report.lines.map(l=>l.client_name),...report.payments.map(p=>p.client_name)])).filter(Boolean).sort((a,b)=>a.localeCompare(b,'es')),[clients,report]);
 const years=useMemo(()=>Array.from(new Set([...report.lines.filter(l=>l.client_name===client).map(l=>localDay(l.delivered_at).slice(0,4)),...report.payments.filter(p=>p.client_name===client).map(p=>p.paid_on.slice(0,4))])).sort().reverse(),[report,client]);
 const clientLines=report.lines.filter(l=>l.client_name===client),clientPayments=report.payments.filter(p=>p.client_name===client);
 const yearLines=clientLines.filter(l=>localDay(l.delivered_at).startsWith(`${year}-`)),yearPayments=clientPayments.filter(p=>p.paid_on.startsWith(`${year}-`));
 const months=Array.from(new Set([...yearLines.map(l=>localDay(l.delivered_at).slice(5,7)),...yearPayments.map(p=>p.paid_on.slice(5,7))])).sort();
 const monthLines=yearLines.filter(l=>localDay(l.delivered_at).slice(5,7)===month);
 const monthPayments=yearPayments.filter(p=>p.paid_on.slice(5,7)===month);
 const paid=(items:FinancePayment[])=>items.filter(p=>!p.reversed).reduce((n,p)=>n+Number(p.amount_mxn),0);
 const nameOf=(id:string)=>people.find(p=>p.id===id)?.full_name??id;
 const exportTable=(kind:'csv'|'pdf')=>{const selected=section==='deliveries'?monthLines:yearLines;
  const title=`${section==='deliveries'?'Entregas':'Estado de cuenta'} · ${client} · ${year}${section==='deliveries'?`-${month}`:''}`;
  const total=totals(selected,clientPayments),records=section==='deliveries'?
   [['Fecha','Folio','Kg destino','MXN/kg','Importe MXN'],...selected.map(l=>[localDay(l.delivered_at),l.folio,l.net_kg,l.price_mxn_per_kg??'Precio pendiente',l.amount_mxn??'']),['TOTAL','',total.kg,'',total.amount]]:
   [['Mes','Kg','Entregas MXN','Pagos recibidos MXN','Aplicado MXN','Saldo MXN'],...months.map(m=>{const ls=yearLines.filter(l=>localDay(l.delivered_at).slice(5,7)===m),t=totals(ls,clientPayments);return [monthName(m),t.kg,t.amount,paid(yearPayments.filter(p=>p.paid_on.slice(5,7)===m)),t.applied,t.amount-t.applied]}),['TOTAL',total.kg,total.amount,paid(yearPayments),total.applied,total.amount-total.applied],['ANTICIPOS SIN APLICAR','','',advances(clientPayments),'','']];
  const payments=section==='payments'?([[],['Pagos: fecha','Referencia','Monto MXN','Aplicado MXN','Anticipo MXN','Estado'],...yearPayments.map(p=>[p.paid_on,p.reference,p.amount_mxn,p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0),Number(p.amount_mxn)-p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0),p.reversed?'REVERTIDO':'Vigente'])] as (string|number|null)[][]):[];
  const rows=[...records,...payments] as (string|number|null)[][];
  const basename=`${section}-${fileName(client)}-${year}${section==='deliveries'?`-${month}`:''}`;
  if(kind==='csv')download(new Blob([csv(rows)],{type:'text/csv;charset=utf-8'}),`${basename}.csv`);
  else download(financePdf(title,rows.map(r=>r.join(' | '))),`${basename}.pdf`)
 };
 const savePrice=(tripId:string)=>act(async()=>{if(!supabase)throw Error('Supabase no disponible');const {error}=await supabase.rpc('finance_set_trip_price',{p_trip:tripId,p_price:parseAmount(price,4),p_reason:reason.trim()});if(error)throw Error(error.message);setPriceTrip('');setPrice('');setReason('')});
 const saveRate=()=>act(async()=>{if(!supabase)throw Error('Supabase no disponible');if(!/^\d{4}-\d{2}-\d{2}$/.test(rateFrom))throw Error('Indica la vigencia AAAA-MM-DD');const {error}=await supabase.rpc('finance_set_client_price',{p_org:organizationId,p_client:client,p_from:rateFrom,p_price:parseAmount(price,4),p_reason:reason.trim()});if(error)throw Error(error.message);setPrice('');setReason('');setRateFrom('')});
 const recordPayment=()=>act(async()=>{if(!supabase)throw Error('Supabase no disponible');const amount=parseAmount(paymentAmount,2),allocations=Object.entries(allocationInputs).filter(([,v])=>v.trim()).map(([trip_id,v])=>({trip_id,amount_mxn:parseAmount(v,2)}));
  if(allocations.reduce((n,a)=>n+a.amount_mxn,0)>amount)throw Error('La suma aplicada supera el pago');if(!/^\d{4}-\d{2}-\d{2}$/.test(paymentDate))throw Error('Fecha AAAA-MM-DD inválida');
  let path:string|null=null;if(receipt){if(!['image/jpeg','image/png','application/pdf'].includes(receipt.type)||receipt.size>10485760)throw Error('El comprobante debe ser JPG, PNG o PDF de hasta 10 MB');const {data:{user}}=await supabase.auth.getUser();if(!user)throw Error('Sesión vencida');path=`${organizationId}/${user.id}/${crypto.randomUUID()}.${receipt.type==='application/pdf'?'pdf':receipt.type==='image/png'?'png':'jpg'}`;const {error}=await supabase.storage.from('finance-receipts').upload(path,receipt,{contentType:receipt.type,upsert:false});if(error)throw Error(error.message)}
  const {error}=await supabase.rpc('finance_record_payment',{p_org:organizationId,p_client:client,p_paid_on:paymentDate,p_amount:amount,p_reference:reference.trim(),p_receipt_path:path,p_allocations:allocations});if(error)throw Error(error.message);setPaymentAmount('');setReference('');setAllocationInputs({});setReceipt(null)
 });
 const allocateAdvance=(paymentId:string)=>act(async()=>{if(!supabase)throw Error('Supabase no disponible');const allocations=Object.entries(allocationInputs).filter(([,v])=>v.trim()).map(([trip_id,v])=>({trip_id,amount_mxn:parseAmount(v,2)}));if(!allocations.length)throw Error('Asigna un importe a un viaje');const {error}=await supabase.rpc('finance_allocate_payment',{p_payment:paymentId,p_allocations:allocations});if(error)throw Error(error.message);setAllocationInputs({});setAdvanceId('')});
 const reverse=()=>act(async()=>{if(!supabase)throw Error('Supabase no disponible');const {error}=await supabase.rpc('finance_reverse_payment',{p_payment:reversalId,p_reason:reversalReason.trim()});if(error)throw Error(error.message);setReversalId('');setReversalReason('')});
 const openReceipt=async(path:string)=>{if(!supabase)return;const {data,error}=await supabase.storage.from('finance-receipts').createSignedUrl(path,60);if(error||!data)throw Error(error?.message??'No se pudo abrir el comprobante');if(Platform.OS==='web')window.open(data.signedUrl,'_blank','noopener,noreferrer')};
 const allocationEditor=(max?:number)=><View>{clientLines.filter(l=>l.amount_mxn!=null).map(l=>{const t=totals([l],clientPayments);const remaining=Math.max(0,t.amount-t.applied);return remaining>0?<Input key={l.trip_id} label={`${l.folio} · saldo ${money(remaining)} · aplicar MXN`} value={allocationInputs[l.trip_id]??''} onChange={v=>setAllocationInputs(x=>({...x,[l.trip_id]:v}))} placeholder="Opcional"/>:null})}{max!=null&&<Text style={style.small}>Disponible de este pago: {money(max)}</Text>}</View>;
 return <View style={style.card}><Text style={style.heading}>Finanzas por cliente · MXN</Text><Text style={style.small}>Sólo ADMIN. Se consideran viajes DELIVERED con ticket DESTINATION legible y confirmado. Los precios y pagos no alteran tickets ni expedientes.</Text>{practice&&<Text style={style.small}>PRUEBA OFFLINE · datos financieros separados de la operación real.</Text>}{error?<Text style={style.error}>{error}</Text>:null}{!loaded?<Button label="Reintentar carga financiera" onPress={()=>void act(async()=>{})} disabled={busy}/>:<>
 <Button label={section==='deliveries'?'✓ Entregas por cliente / año / mes':'Entregas por cliente / año / mes'} onPress={()=>{setSection('deliveries');setMonth('')}}/><Button label={section==='payments'?'✓ Estado de cuenta y pagos':'Estado de cuenta y pagos'} onPress={()=>{setSection('payments');setMonth('')}}/>
 {!client?<><Text style={style.sub}>Carpetas de clientes</Text>{names.map(n=><Button key={n} label={`📁 ${n}`} onPress={()=>{setClient(n);setYear('');setMonth('')}}/>)}</>:<><Button label={`← Clientes / ${client}`} onPress={()=>{setClient('');setYear('');setMonth('')}}/>
 {!year?<><Text style={style.sub}>📁 {client} / años</Text>{years.map(y=><Button key={y} label={`📁 ${y}`} onPress={()=>{setYear(y);setMonth('')}}/>)}{!years.length&&<Text style={style.small}>Aún no hay entregas ni pagos confirmados.</Text>}</>:<><Button label={`← ${client} / años`} onPress={()=>{setYear('');setMonth('')}}/>
 {section==='deliveries'&&!month?<><Text style={style.sub}>📁 {client} / {year} / meses</Text>{months.map(m=><Button key={m} label={`📁 ${monthName(m)} · ${yearLines.filter(l=>localDay(l.delivered_at).slice(5,7)===m).length} viajes`} onPress={()=>setMonth(m)}/>)}</>:null}
 {section==='deliveries'&&month?<><Button label={`← ${year} / meses`} onPress={()=>setMonth('')}/><Text style={style.sub}>Entregas · {monthName(month)} {year}</Text><View style={style.table}>{['Fecha','Folio','Kg','MXN/kg','Importe'].map(h=><Text key={h} style={style.cell}>{h}</Text>)}</View>{monthLines.map(l=><View key={l.trip_id} style={style.row}><View style={style.table}>{[localDay(l.delivered_at),l.folio,kilos(Number(l.net_kg)),l.price_mxn_per_kg==null?'Pendiente':money(Number(l.price_mxn_per_kg)),l.amount_mxn==null?'—':money(Number(l.amount_mxn))].map((v,i)=><Text key={i} style={style.cell}>{v}</Text>)}</View><Button label={priceTrip===l.trip_id?'Cancelar ajuste':l.price_mxn_per_kg==null?'Registrar precio':'Ajustar precio'} onPress={()=>{setPriceTrip(priceTrip===l.trip_id?'':l.trip_id);setPrice('');setReason('')}}/>{priceTrip===l.trip_id&&<><Input label="Precio MXN por kg" value={price} onChange={setPrice}/><Input label="Motivo de registro o ajuste (mínimo 10 caracteres)" value={reason} onChange={setReason}/><Button label="Guardar precio auditado" onPress={()=>savePrice(l.trip_id)} disabled={busy}/></>}</View>)}<Text style={style.sub}>Total: {kilos(totals(monthLines,clientPayments).kg)} kg · {money(totals(monthLines,clientPayments).amount)}</Text>{totals(monthLines,clientPayments).pending>0&&<Text style={style.error}>{totals(monthLines,clientPayments).pending} viaje(s) sin precio; importe parcial, no total definitivo.</Text>}<Button label="Exportar CSV" onPress={()=>exportTable('csv')}/><Button label="Exportar PDF" onPress={()=>exportTable('pdf')}/></>:null}
 {section==='payments'&&<><Text style={style.sub}>Estado de cuenta · {client} · {year}</Text><View style={style.table}>{['Mes','Kg','Entregas','Recibido','Aplicado','Saldo'].map(h=><Text key={h} style={style.cell}>{h}</Text>)}</View>{months.map(m=>{const ls=yearLines.filter(l=>localDay(l.delivered_at).slice(5,7)===m),t=totals(ls,clientPayments);return <View key={m} style={style.row}><View style={style.table}>{[monthName(m),kilos(t.kg),money(t.amount),money(paid(yearPayments.filter(p=>p.paid_on.slice(5,7)===m))),money(t.applied),money(t.amount-t.applied)].map((x,i)=><Text key={i} style={style.cell}>{x}</Text>)}</View></View>})}{(()=>{const t=totals(yearLines,clientPayments);return <><Text style={style.sub}>Año: {kilos(t.kg)} kg · Entregas {money(t.amount)} · Pagos recibidos {money(paid(yearPayments))} · Aplicados a viajes de {year} {money(t.applied)} · Deuda pendiente {money(t.amount-t.applied)}</Text>{t.pending>0&&<Text style={style.error}>{t.pending} viaje(s) sin precio: deuda parcial.</Text>}</>})()}<Text style={style.small}>Anticipos vigentes del cliente sin aplicar: {money(advances(clientPayments))}. Los pagos recibidos se agrupan por fecha de pago; las aplicaciones, por mes de entrega. Una reversión conserva el historial y deja de sumar.</Text><Button label="Exportar CSV" onPress={()=>exportTable('csv')}/><Button label="Exportar PDF" onPress={()=>exportTable('pdf')}/><Text style={style.sub}>Registro de pagos</Text>{yearPayments.map(p=><View key={p.id} style={style.row}><Text style={style.text}>{p.paid_on} · {p.reference} · {money(Number(p.amount_mxn))} · {p.reversed?'REVERTIDO':'Vigente'}</Text><Text style={style.small}>Aplicado {money(p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0))} · anticipo {money(Number(p.amount_mxn)-p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0))} · {nameOf(p.created_by)} · {new Date(p.created_at).toLocaleString('es-MX')}</Text>{p.allocations.map(a=><Text key={a.trip_id} style={style.small}>↳ {clientLines.find(l=>l.trip_id===a.trip_id)?.folio??a.trip_id}: {money(Number(a.amount_mxn))}</Text>)}{p.reversal_reason&&<Text style={style.error}>Reversión: {p.reversal_reason}</Text>}{p.receipt_path&&<Button label="Ver comprobante" onPress={()=>void openReceipt(p.receipt_path!).catch(e=>setError(String(e)))}/>} {!p.reversed&&Number(p.amount_mxn)>p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0)&&<Button label="Aplicar anticipo a viajes" onPress={()=>{setAdvanceId(p.id);setAllocationInputs({})}}/>}{advanceId===p.id&&<>{allocationEditor(Number(p.amount_mxn)-p.allocations.reduce((n,a)=>n+Number(a.amount_mxn),0))}<Button label="Confirmar aplicaciones" onPress={()=>allocateAdvance(p.id)} disabled={busy}/></>}{!p.reversed&&<Button label="Revertir pago con motivo" onPress={()=>setReversalId(p.id)}/>} {reversalId===p.id&&<><Input label="Motivo de reversión" value={reversalReason} onChange={setReversalReason}/><Button label="Confirmar reversión auditada" onPress={reverse} disabled={busy}/></>}</View>)}</>}
 </>}
 <View style={style.card}><Text style={style.sub}>Precio con vigencia para {client}</Text><Input label="Inicio AAAA-MM-DD (posterior a entregas confirmadas)" value={rateFrom} onChange={setRateFrom}/><Input label="Precio MXN/kg" value={priceTrip?'':price} onChange={setPrice}/><Input label="Motivo (mínimo 10 caracteres)" value={priceTrip?'':reason} onChange={setReason}/><Button label="Registrar precio futuro" onPress={saveRate} disabled={busy||!!priceTrip}/><Text style={style.small}>Para viajes ya entregados, registra el precio individual. Una nueva tarifa no cambia el precio de viajes anteriores.</Text></View>
 <View style={style.card}><Text style={style.sub}>Registrar pago o anticipo para {client}</Text><Input label="Fecha AAAA-MM-DD" value={paymentDate} onChange={setPaymentDate}/><Input label="Monto MXN" value={paymentAmount} onChange={setPaymentAmount}/><Input label="Referencia única" value={reference} onChange={setReference}/>{Platform.OS==='web'&&<input aria-label="Comprobante opcional" type="file" accept="image/jpeg,image/png,application/pdf" onChange={e=>setReceipt(e.currentTarget.files?.[0]??null)}/>}<Text style={style.small}>Aplicaciones opcionales; el resto queda como anticipo. Viajes con precio confirmado:</Text>{allocationEditor()}<Button label="Registrar pago" onPress={recordPayment} disabled={busy}/></View>
 <Text style={style.sub}>Historial de precios</Text>{report.rules.filter(x=>x.client_name?.toLowerCase()===client.toLowerCase()).map(x=><Text key={x.id} style={style.small}>Tarifa desde {x.effective_on}: {money(Number(x.price_mxn_per_kg))}/kg · {x.reason} · {nameOf(x.created_by)} · {new Date(x.created_at).toLocaleString('es-MX')}</Text>)}{report.revisions.filter(x=>clientLines.some(l=>l.trip_id===x.trip_id)).map(x=><Text key={x.id} style={style.small}>Viaje {clientLines.find(l=>l.trip_id===x.trip_id)?.folio}: {money(Number(x.price_mxn_per_kg))}/kg · {x.reason} · {nameOf(x.created_by)} · {new Date(x.created_at).toLocaleString('es-MX')}</Text>)}
 </>}
 </>}
 </View>;
}
